##**INSTALL NUMPY**

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# IMPORT


In [ ]:
import numpy as np

## **Check Version**

In [ ]:
np.__version__

'1.22.4'

# Creating empty array

In [ ]:
x = np.array([])

In [ ]:
x

array([], dtype=float64)

In [ ]:
type(x)  # numpy. n dimensional array

numpy.ndarray

#Creating 1D array

In [ ]:
x = np.array([5,5.4,1,3.2,4,5])

In [ ]:
x

array([5. , 5.4, 1. , 3.2, 4. , 5. ])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
len(x)

6

In [ ]:
x.shape

(6,)

In [ ]:
x[4]

4.0

In [ ]:
x[-1]

5.0

In [ ]:
x[-2]

4.0

In [ ]:
x[:2]

array([5. , 5.4])

In [ ]:
x[2:4]

array([1. , 3.2])

In [ ]:
x[1:5]

array([5.4, 1. , 3.2, 4. ])

In [ ]:
x.append(55)

AttributeError: ignored

In [ ]:
np.append(x,55)

array([ 5. ,  5.4,  1. ,  3.2,  4. ,  5. , 55. ])

# Difference between list and numpy array

In [ ]:
about = ['Kritazya', 'PVT', False, 25,26.6]
about


['Kritazya', 'PVT', False, 25, 26.6]

In [ ]:
type(about[2])

bool

In [ ]:
about_array = np.array(about)
about_array

array(['Kritazya', 'PVT', 'False', '25', '26.6'], dtype='<U32')

In [ ]:
type(about_array[2])

numpy.str_

# List supports multiple datatype while numpy array is homogenous

In [ ]:
list1 = [1,1,1]
x = np.array([list1], dtype= np.int0)
x


array([[1, 1, 1]])

In [ ]:
import random
random.seed(80)
data = [random.randint(1,10) for item in range(100000)]

In [ ]:
print(data)

[5, 7, 9, 7, 6, 6, 9, 7, 6, 1, 9, 7, 4, 10, 1, 7, 4, 3, 9, 10, 1, 3, 8, 10, 3, 3, 4, 6, 6, 10, 3, 4, 5, 5, 2, 6, 2, 1, 1, 3, 9, 5, 5, 6, 10, 10, 1, 6, 8, 2, 4, 8, 9, 6, 9, 1, 8, 4, 5, 6, 8, 6, 1, 9, 1, 7, 4, 2, 2, 1, 3, 1, 10, 5, 6, 8, 1, 9, 2, 6, 8, 3, 8, 7, 3, 3, 4, 7, 7, 3, 2, 2, 3, 7, 5, 9, 6, 5, 9, 9, 8, 4, 10, 3, 10, 9, 6, 7, 9, 5, 2, 10, 1, 5, 6, 7, 7, 1, 4, 2, 6, 4, 9, 5, 5, 6, 10, 5, 6, 10, 3, 2, 4, 3, 3, 3, 2, 8, 5, 1, 8, 3, 2, 2, 4, 10, 1, 4, 5, 6, 6, 2, 6, 3, 4, 6, 7, 7, 7, 9, 2, 8, 8, 7, 10, 10, 1, 2, 1, 6, 8, 4, 3, 10, 5, 5, 5, 6, 7, 10, 3, 9, 8, 4, 9, 3, 2, 6, 1, 9, 5, 4, 7, 10, 8, 5, 4, 9, 2, 7, 2, 6, 8, 4, 3, 6, 5, 5, 2, 8, 8, 3, 3, 5, 5, 3, 2, 2, 1, 7, 2, 7, 1, 4, 7, 7, 6, 5, 3, 2, 2, 1, 2, 7, 4, 10, 2, 9, 6, 10, 3, 3, 10, 2, 10, 5, 9, 2, 1, 2, 1, 7, 8, 2, 3, 4, 6, 10, 2, 3, 6, 3, 1, 5, 6, 10, 4, 5, 6, 2, 2, 4, 9, 6, 3, 10, 7, 6, 7, 3, 5, 9, 5, 2, 3, 8, 9, 1, 7, 1, 3, 2, 10, 2, 10, 3, 3, 5, 8, 5, 7, 2, 4, 1, 1, 5, 5, 8, 9, 5, 9, 8, 4, 6, 1, 6, 8, 6, 6, 2, 4, 3, 3, 2, 

In [ ]:
data_array = np.array(data)
data_array

array([5, 7, 9, ..., 4, 8, 8])

In [ ]:
%%time
sq = [item ** 2 for item in data]

CPU times: user 30.1 ms, sys: 0 ns, total: 30.1 ms
Wall time: 34.9 ms


In [ ]:
%%time
sq = data_array**2

CPU times: user 1.35 ms, sys: 27 µs, total: 1.37 ms
Wall time: 5.29 ms


# Besides creating an array from a sequence of elements, you can create an array filled with 0's , 1's , empty - depends on state of memory

In [ ]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5, dtype = np.int8)

array([0, 0, 0, 0, 0], dtype=int8)

In [ ]:
np.zeros(5, dtype = np.float32)

array([0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
np.ones(3, dtype = np.int8)

array([1, 1, 1], dtype=int8)

In [ ]:
np.empty(7)

array([ 5. ,  5.4,  1. ,  3.2,  4. ,  5. , 55. ])

# zeros and ones are used in binary image masking in computer vision

[Binary Image Masking](https://pyimagesearch.com/2021/01/19/image-masking-with-opencv/)

# You can create an array with range of elements

In [ ]:
list(range(15,21))

[15, 16, 17, 18, 19, 20]

In [ ]:
np.arange(15,21)

array([15, 16, 17, 18, 19, 20])

# You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.linspace(0,0.00000233233201, 200)

array([0.00000000e+00, 1.17202614e-08, 2.34405227e-08, 3.51607841e-08,
       4.68810454e-08, 5.86013068e-08, 7.03215681e-08, 8.20418295e-08,
       9.37620909e-08, 1.05482352e-07, 1.17202614e-07, 1.28922875e-07,
       1.40643136e-07, 1.52363398e-07, 1.64083659e-07, 1.75803920e-07,
       1.87524182e-07, 1.99244443e-07, 2.10964704e-07, 2.22684966e-07,
       2.34405227e-07, 2.46125488e-07, 2.57845750e-07, 2.69566011e-07,
       2.81286273e-07, 2.93006534e-07, 3.04726795e-07, 3.16447057e-07,
       3.28167318e-07, 3.39887579e-07, 3.51607841e-07, 3.63328102e-07,
       3.75048363e-07, 3.86768625e-07, 3.98488886e-07, 4.10209147e-07,
       4.21929409e-07, 4.33649670e-07, 4.45369932e-07, 4.57090193e-07,
       4.68810454e-07, 4.80530716e-07, 4.92250977e-07, 5.03971238e-07,
       5.15691500e-07, 5.27411761e-07, 5.39132022e-07, 5.50852284e-07,
       5.62572545e-07, 5.74292806e-07, 5.86013068e-07, 5.97733329e-07,
       6.09453591e-07, 6.21173852e-07, 6.32894113e-07, 6.44614375e-07,
      

In [ ]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])